### PR TITLE
Create download-is-live.php

### PR DESCRIPTION
**Pull request by christ0ph3r**
Sends an email to author when download is published

### CODE REVIEW

**Comment by cklosowski** [comment]
Great idea. Can you add proper plugin headers to this?  This way people can download the raw `.php` file from github and simply drop it in their plugins folder and activate.

A quick example from WordPress.org
```
/*
Plugin Name: Health Check
Plugin URI:  http://wordpress.org/extend/plugins/health-check/
Description: Checks the health of your WordPress install
Version:     0.1-alpha
Author:      The Health Check Team
Author URI:  http://wordpress.org/extend/plugins/health-check/
 */
```

**Comment by christ0ph3r** [comment]
Thanks and done.

**Comment by christ0ph3r** [comment]
@cklosowski

**Comment by cklosowski** [comment]
Made some whitespace changes, and a little fault tolerance if the author is the person publishing the article.

**Comment by cklosowski** [comment]
Converted it to use the EDD Emails class as well so it gets templated:
image

**Comment by christ0ph3r** [comment]
Wow! Nice.  Can you explain to me what this means in the comment?  Does it do anything or is it just helpful information?

 * @param  int $post_id The download id being published
 * @return void

@cklosowski

**Comment by cklosowski** [comment]
Yeah no worries, it's PHPDoc. Basically just documentation so that when someone looks at the code they know what parameters it takes and what type of data it will return.

In this case, it takes in an integer, the post ID. Since this function doesn't return any data it's considered `void` or `returns nothing`. If we returned something we'd specify it's variable type, and a description of the return.

Here's a link to learn more about PHPDoc http://en.wikipedia.org/wiki/PHPDoc

**Comment by christ0ph3r** [comment]
Thanks for the explanation and reference.

**Pull request merged**
