### PR TITLE
FES: email admin on auto-approved vendor application.

### PR DESCRIPTION
**Pull request by mindctrl**

### CODE REVIEW

**Comment by chriscct7** [comment]
These are the wrong hooks:
do_action ( 'fes_register_form_frontend_autoapproved_vendor_email', $save_id, $values ); should be used for emails, and it should use edd_get_option() not the global options

**Comment by chriscct7** [comment]
Also, in a hooked additional email, the contents and subject of the email should be hardcoded not from those options. They won't exist if autoapprove is on

**Comment by mindctrl** [comment]
@chriscct7 that hook doesn't exist in the 2.2.17.

**Comment by mindctrl** [comment]
Also it would be preferable in the future to submit a patch instead of reverting in cases where I may have linked someone directly to the file.

**Comment by chriscct7** [comment]
There is not an applicable action that this type of thing will work on in the current release and continue doing so. This is how this snippet should look, and is supported FES 2.3+

```
add_action ( 'fes_register_form_frontend_autoapproved_vendor_email', 'fes_my_custom_autoapproved_vendor_email', 10, 2 );
function fes_my_custom_autoapproved_vendor_email( $user_id, $values ){
	// email admin
	$to = edd_get_admin_notice_emails();
	$from_name = edd_get_option( 'from_name', get_bloginfo( 'name' ) );
	$from_email = edd_get_option( 'from_email', get_option( 'admin_email' ) );
	$subject = 'Your subject here. ';
	$message = 'Your message here.';
	$type = "post";
	$id = $post_id;
	EDD_FES()->emails->send_email( $to , $from_name, $from_email, $subject, $message, $type, $id, array() );
}
```

**Comment by mindctrl** [comment]
@chriscct7 if you removed the fes_registration_form_frontend_vendor hook in 2.3, you'll probably need to add it back. Hooks and filters are things we won't be able to easily test and removing them entirely feels like it's going to cause us pain. Pinging you directly to see if you can provide a list of hooks and filters that have been removed or changed.

**Comment by chriscct7** [comment]
fes_registration_form_frontend_vendor isn't removed in 2.3, however its not compatible with what you are attempting to accomplish. It fires before a redirect, not when the actual emails were sent, and thus in 2.3, it fires at a point which may or may not be called anymore. Further, the second parameter has slightly different values, as the entire concept of $userdata doesn't exist anymore.

**Pull request merged**
