### PR TITLE
Create change-vendor-pending-message.php

### PR DESCRIPTION
**Pull request by brashrebel**
Changes the message displayed to vendors after they apply and are redirected.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Since this is for FES only, please put it in the extensions folder.

**Comment by brashrebel** [comment]
Whoops!  Don't know how the path got messed up but I'll correct it.

**Comment by pippinsplugins** [comment]
@brashrebel want to update your PR so it merges cleanly?

**Comment by brashrebel** [comment]
Errr...I'm confused now. When I look at the patch it looks like the path is right.

**Comment by pippinsplugins** [comment]
@brashrebel the path is fine, it just doesn't merge cleanly. No worries, I'll fix it up for you.

**Pull request merged**
